export const TEACHERS = [
  {
    id: "TCH-001",
    name: "Dr. Priya Sharma",
    email: "priya.sharma@school.edu",
    avatar: "PS",
    avatarColor: "bg-violet-500",
    department: "Science",
    subject: "Physics",
    subjectBg: "bg-violet-100",
    subjectText: "text-violet-700",
    classes: ["10-A", "11-B", "12-A"],
    experience: 9,
    attendance: 96,
    status: "Active",
    pendingTasks: 2,
  },
  {
    id: "TCH-002",
    name: "Mr. Arjun Mehta",
    email: "arjun.mehta@school.edu",
    avatar: "AM",
    avatarColor: "bg-sky-500",
    department: "Mathematics",
    subject: "Mathematics",
    subjectBg: "bg-sky-100",
    subjectText: "text-sky-700",
    classes: ["9-B", "10-B"],
    experience: 6,
    attendance: 89,
    status: "Active",
    pendingTasks: 5,
  },
  {
    id: "TCH-003",
    name: "Ms. Fatima Khan",
    email: "fatima.khan@school.edu",
    avatar: "FK",
    avatarColor: "bg-rose-500",
    department: "Languages",
    subject: "English",
    subjectBg: "bg-rose-100",
    subjectText: "text-rose-700",
    classes: ["8-A", "8-B", "9-A"],
    experience: 4,
    attendance: 72,
    status: "On Leave",
    pendingTasks: 8,
  },
  {
    id: "TCH-004",
    name: "Mr. Ravi Kumar",
    email: "ravi.kumar@school.edu",
    avatar: "RK",
    avatarColor: "bg-emerald-500",
    department: "Science",
    subject: "Chemistry",
    subjectBg: "bg-emerald-100",
    subjectText: "text-emerald-700",
    classes: ["11-A", "12-B"],
    experience: 12,
    attendance: 98,
    status: "Active",
    pendingTasks: 1,
  },
  {
    id: "TCH-005",
    name: "Ms. Sneha Patil",
    email: "sneha.patil@school.edu",
    avatar: "SP",
    avatarColor: "bg-amber-500",
    department: "Social Studies",
    subject: "History",
    subjectBg: "bg-amber-100",
    subjectText: "text-amber-700",
    classes: ["6-A", "7-A", "7-B"],
    experience: 3,
    attendance: 81,
    status: "Active",
    pendingTasks: 3,
  },
  {
    id: "TCH-006",
    name: "Dr. Suresh Nair",
    email: "suresh.nair@school.edu",
    avatar: "SN",
    avatarColor: "bg-indigo-500",
    department: "Mathematics",
    subject: "Statistics",
    subjectBg: "bg-indigo-100",
    subjectText: "text-indigo-700",
    classes: ["11-C", "12-C"],
    experience: 15,
    attendance: 94,
    status: "Active",
    pendingTasks: 0,
  },
  {
    id: "TCH-007",
    name: "Ms. Anjali Verma",
    email: "anjali.verma@school.edu",
    avatar: "AV",
    avatarColor: "bg-pink-500",
    department: "Arts",
    subject: "Fine Arts",
    subjectBg: "bg-pink-100",
    subjectText: "text-pink-700",
    classes: ["6-B", "8-C"],
    experience: 2,
    attendance: 65,
    status: "Inactive",
    pendingTasks: 11,
  },
  {
    id: "TCH-008",
    name: "Mr. Vikram Singh",
    email: "vikram.singh@school.edu",
    avatar: "VS",
    avatarColor: "bg-teal-500",
    department: "Physical Ed.",
    subject: "Physical Ed.",
    subjectBg: "bg-teal-100",
    subjectText: "text-teal-700",
    classes: ["All Grades"],
    experience: 7,
    attendance: 91,
    status: "Active",
    pendingTasks: 2,
  },
];

export const DEPARTMENTS = [
  "All Departments",
  "Science",
  "Mathematics",
  "Languages",
  "Social Studies",
  "Arts",
  "Physical Ed.",
];

export const SUBJECTS = [
  "All Subjects",
  "Physics",
  "Mathematics",
  "English",
  "Chemistry",
  "History",
  "Statistics",
  "Fine Arts",
  "Physical Ed.",
];

export const STATUSES = ["All Status", "Active", "On Leave", "Inactive"];

export const EXPERIENCE_RANGES = [
  "Any Experience",
  "0–3 yrs",
  "4–7 yrs",
  "8–12 yrs",
  "12+ yrs",
];